#!/bin/sh
msg=$(cat $1)
first_letter=${msg:0:1}
if [[ $first_letter =~ [[:lower:]] ]]; then
    echo "Sorry, commit failed. First letter must be in uppercase!"
    exit 1
fi;
# Check non-ascii
# \t existed in .git/COMMIT_EDITMSG when git commit --amend
\grep '[^ -~[:space:]]\+' $1 &>/dev/null
if [[ $? -eq 0 ]]; then
    echo "Sorry, commit failed. No Chinese plz!"
    exit 1
fi;
# Must reference an issue
if ! grep -i '\(Merge\|Hotfix\|#[[:digit:]]\+\)' $1 &>/dev/null; then
    echo "Sorry, commit failed. Reference an issue plz!"
    exit 2
fi