# Generated by Django 2.1 on 2018-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover_picture',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='Cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='course_picture', verbose_name='课程图片'),
        ),
        migrations.DeleteModel(
            name='Cover_picture',
        ),
    ]
