# Generated by Django 2.1 on 2018-08-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exists',
        ),
    ]
