# Generated by Django 2.1 on 2018-08-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Manage_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='course_price',
            field=models.FloatField(verbose_name='支付金额'),
        ),
    ]
