# Generated by Django 2.1 on 2018-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Manage_order',
            field=models.BooleanField(default=False),
        ),
    ]
