# Generated by Django 2.1 on 2018-08-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0002_auto_20180821_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_price',
            new_name='amount_of_money',
        ),
    ]
