# Generated by Django 2.1 on 2018-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0002_course_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, verbose_name='邀请码')),
            ],
        ),
    ]
