# Generated by Django 2.1 on 2018-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0002_manager_manage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course_price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_of_money',
            field=models.FloatField(default=0.0, verbose_name='支付金额'),
        ),
    ]
