# Generated by Django 2.1 on 2018-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0003_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exists',
        ),
        migrations.AlterField(
            model_name='course',
            name='whole_introduction',
            field=models.TextField(blank=True, null=True, verbose_name='详解'),
        ),
    ]
