# Generated by Django 2.1 on 2018-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0003_course_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Is_distory',
            new_name='Is_destroy',
        ),
        migrations.AlterField(
            model_name='course_picture',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_picture',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
