# Generated by Django 2.1 on 2018-08-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0004_auto_20180822_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cover_picture', models.ImageField(blank=True, null=True, upload_to='course_picture', verbose_name='课程图片')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_lab.Course')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_protrait',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos'),
        ),
    ]
