# Generated by Django 2.1 on 2018-08-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0004_auto_20180813_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Is_comment',
            new_name='Can_comment',
        ),
    ]
