# Generated by Django 2.1 on 2018-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0004_auto_20180824_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, default='2100实验室用户', max_length=15, null=True),
        ),
    ]
