# Generated by Django 2.1 on 2018-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0005_auto_20180824_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='2100实验室用户', max_length=15),
        ),
    ]
