# Generated by Django 2.1 on 2018-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lab', '0006_auto_20180813_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
