#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.vue' '*.js')
if [[ "$STAGED_FILES" = "" ]]; then
  break
fi
PASS=true
# Check for eslint
echo "Validating Javascript:"
which eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install ESlint"
  exit 1
fi
for FILE in $STAGED_FILES
do
  eslint "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "ESLint Passed: $FILE"
  else
    echo "ESLint Failed: $FILE"
    PASS=false
  fi
done
echo "eslint validation completed!"

STAGED_FILES_STYLE=$(git diff --cached --name-only --diff-filter=ACM -- '*.css')
if [[ "$STAGED_FILES_STYLE" = "" ]]; then
  break
fi

# Check for stylelint
echo "Validating STYLE:"
which stylelint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install STYLElint"
  exit 1
fi
for FILE in $STAGED_FILES_STYLE
do
  stylelint "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "STYLELint Passed: $FILE"
  else
    echo "STYLELint Failed: $FILE"
    PASS=false
  fi
done
echo "STYLE validation completed!"

STAGED_FILES_PY=$(git diff --cached --name-only --diff-filter=ACM -- '*.py')
if [[ "$STAGED_FILES_PY" = "" ]]; then
  break
fi

# Check for pylint
echo "Validating PYLint:"
which pylint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PYlint"
  exit 1
fi
for FILE in $STAGED_FILES_PY
do
  pylint "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "pylint Passed: $FILE"
  else
    echo "pylint Failed: $FILE"
    PASS=false
  fi
done
echo "pylint validation completed!"

#return result!
if ! $PASS; then
  echo "COMMIT FAILED! "
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi
exit $?